In [17]:
%pip install numpy
def homework(message):
    print("\n>>>>>", message, "\n")

Note: you may need to restart the kernel to use updated packages.


In [18]:
import numpy as np
temperature = [20.1, 20.1, 20.2, 20.4]
print(temperature)

t1 = temperature * 5

print(f"При множенні на 5 маємо: {t1}")
homework("Множимо на масив")

t1 = [ x*5 for x in temperature]
print(f"Тепер отримаємо: {t1}")
homework("Множення на елменти масивів")

t2 = np.array(temperature)
print("Масив з використанням методів NumPy", t2)

t3 = t2 * 5
print("При множенні на 5 отримуємо:", t3)

[20.1, 20.1, 20.2, 20.4]
При множенні на 5 маємо: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]

>>>>> Множимо на масив 

Тепер отримаємо: [100.5, 100.5, 101.0, 102.0]

>>>>> Множення на елменти масивів 

Масив з використанням методів NumPy [20.1 20.1 20.2 20.4]
При множенні на 5 отримуємо: [100.5 100.5 101.  102. ]


In [19]:
print("Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:")
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1],
                          [2],
                          [3],
                          [4]])
print(vector_row, "\nВектор має розмір", vector_row.shape)
print(vector_column, "\nВектор має розмір", vector_column.shape)

Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:
[[ 1 -5  3  2  4]] 
Вектор має розмір (1, 5)
[[1]
 [2]
 [3]
 [4]] 
Вектор має розмір (4, 1)


In [23]:
start = 5
size_of_vec = 100
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {x[0:5]} та методом arange: {a[0:5]}")
print(f"The entire range of numbers generated by the arange method: {a}")

a = np.arange(start, size_of_vec)
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[0]}")
homework("Виведіть останній діапазон в згенерованому масиві.")

x = range(start, size_of_vec)
print("Те саме але з вбудованою функцією range:", x)
print("Власне вивід значень:", list(x)[0], )
mid = int(len(x) / 2)
print("Число з середини діапазону x:", x[mid])

# дробові числа
x = np.arange(10.4)
print("Будем мати:", x)
# крок
x = np.arange(0.5, 4, 0.5)
print("З кроком 0.5:", x)
# Заокруглення
x = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", x, "\n Зерніть уагу на заокруглення")
step = 0.0004
a = np.arange(start, start+size_of_vec*step, step)
print(a)
y = x * 2.5
print("Після перемноження:", y)
result = (a[50] ** 2) / 0.4
print("Result:", result)


Масив згенерований простим range: range(0, 5) та методом arange: [0 1 2 3 4]
The entire range of numbers generated by the arange method: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Можемо задавати початок генерації вектора, перший елемент: 5

>>>>> Виведіть останній діапазон в згенерованому масиві. 

Те саме але з вбудованою функцією range: range(5, 100)
Власне вивід значень: 5
<class 'float'>
Будем мати: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
З кроком 0.5: [0.5 1.  1.5 2.  2.5 3.  3.5]
З кроком 0.08: [0.04 0.12 0.2  0.28 0.36 0.44 0.52 0.6  0.68 0.76 0.84 0.92 1.   1.08
 1.16 1.24 1.32 1.4  1.48 1.56 1.64 1.72 1.8 ] 
 Зерніть уагу на заокруглення

>>>>> Згенеруйте значення де крок буде мати чотири нулі після коми, яким б

In [ ]:
start = 5
size_of_vec = 100
a = np.linspace(start, size_of_vec)
print(f"Згенерували {len(a)} чисел в діапазоні {a[0]} до {a[-1]}")
#print(f"Власне числа: {a}")
homework("Виведіть кожне друге число згенерованого діапазону. Тут будее потрібен цикл :)")
a = np.linspace(start, size_of_vec, num=(size_of_vec-start+1))
result = a[::2]
print(result)
print("Можна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(a)
homework("Збільшіть кількість чисел до 100. Виведіть перших та останніх 10.")
a = np.linspace(start, size_of_vec, num=100)
print("First 10 numbers:", a[:10])
print("Last 10 numbers:", a[-10:])

print("""Як бачимо перше та останнє значення завжди входять у згенерований діапазон.
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.
""")

print(np.linspace(start, size_of_vec, 5, endpoint=False))
homework("Спробуйте самі порахуавти крок.")


_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print(f"Для порівняння, ми можемо визначити крок автоматично, у нашому випадку це {sp_1} та {sp_2}")
homework("Чому маємо такий крок?")

In [24]:
examples = {
    'Скаляр': np.array(1),
    'Вектор Рядок': np.array([1, 2, 3]),
    'Вектор Стовпець': np.array([[1], [2], [3]]),
    'Матриця': np.array([[1, 2],[3, 4], [5, 6]]),
    'Багатовимірна Матриця': np.array([ [[111, 112], [121, 122]],
                                        [[211, 212], [221, 222]],
                                        [[311, 312], [321, 322]] ])
}
for key in examples:
    print(f"Розглядаємо приклад з {key}. \nЗначення x буде: \n", examples[key])
    print(f"Тип {key} x: ", type(examples[key]))
    print(f"Розмірність/вимір {key} x:", np.ndim(examples[key]))
    print(f"Форма {key} x: ", examples[key].shape)
    print(f"Кількість елементів х: {np.size(examples[key])}")
    print("-=-"*10)

homework("""Як Ви думаєте чому маємо такий результат для функції np.ndim (Розмірність/вимір/dimension).
Чому значення для векторів та матриць однакове та не співпдає з значенням shape?
Задайте власні вектори з різними числами.""")
print('Функція np.ndim повертає кількість вимірів у масиві. У наведеному вище коді ми бачимо, що для скалярів, векторів-рядків і векторів-стовпців кількість вимірів дорівнює 1. Для матриць кількість вимірів дорівнює 2. Для багатовимірних матриць кількість вимірів дорівнює 3.З іншого боку, атрибут shape повертає форму масиву, тобто кількість елементів уздовж кожного')

Розглядаємо приклад з Скаляр. 
Значення x буде: 
 1
Тип Скаляр x:  <class 'numpy.ndarray'>
Розмірність/вимір Скаляр x: 0
Форма Скаляр x:  ()
Кількість елементів х: 1
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Рядок. 
Значення x буде: 
 [1 2 3]
Тип Вектор Рядок x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Рядок x: 1
Форма Вектор Рядок x:  (3,)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Стовпець. 
Значення x буде: 
 [[1]
 [2]
 [3]]
Тип Вектор Стовпець x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Стовпець x: 2
Форма Вектор Стовпець x:  (3, 1)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Матриця. 
Значення x буде: 
 [[1 2]
 [3 4]
 [5 6]]
Тип Матриця x:  <class 'numpy.ndarray'>
Розмірність/вимір Матриця x: 2
Форма Матриця x:  (3, 2)
Кількість елементів х: 6
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Багатовимірна Матриця. 
Значення x буде: 
 [[[111 112]
  [121 122]]

 [[211 

In [ ]:
examples = {
    '5 рядків': np.array([[1], [2], [3], [4], [5]]),
    '5 стовпців': np.array([[1, 2, 3, 4, 5]]),
    '5 елементів': np.array([[[1, 2, 3, 4, 5]]])
    }
for a in examples:
    print(f"Для {a} маємо shape: \n{examples[a].shape} \nта вигляд: \n{examples[a]}")

homework(f"Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів.")
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([[1, 2, 3],[4, 5, 6]])
array3 = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]]])

print("Array1 Shape:", array1.shape)
print("Array2 Shape:", array2.shape)
print("Array3 Shape:", array3.shape)

In [ ]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
print(f"""Масив: {F}
Виміри: {F.shape}
Памятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву:\n {F[0]}
Другий:\n {F[1]}
Останній, {len(F)}: \n {F[7]}""")

print(f"""Можемо скористатись відємними індексами якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент:\n {F[-1]}
Передостанній:\n {F[-2]}""")

homework("Попрактикуйтесь доступатись до елементів, виведіть декілька елементів різними способами.")
print(F[:3]) # [1 1 2]
print(F[2:5]) # [2 3 5]
print(F[-3:]) # [8 13 21]

In [25]:
A = np.array([ [3.4, 8.7, 9.9],
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8],
               [7.0, -3.9, 5.1]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення то візьметься цілий рядок:
    Перший рядок: {A[0]}
    Останній рядок: {A[-1]}
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи):
    Перший стовпець: {A[:,0]}
    Останній стовпець: {A[:,-1]}
Потрібно задавати два значення для отримання конкретного елемента:
    Перший елемент: {A[0][0]} або {A[0, 0]}
    Останній елемент: {A[3][2]} або {A[-1][-1]} або {A[3, -1]}
""")

homework("Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементів які належать діагоналі.")
for i in range(A.shape[0]):
    print(A[i][i])

Масив:
[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]
 [ 7.  -3.9  5.1]]
Виміри: (4, 3)
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення то візьметься цілий рядок:
    Перший рядок: [3.4 8.7 9.9]
    Останній рядок: [ 7.  -3.9  5.1]
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи):
    Перший стовпець: [3.4 1.1 4.1 7. ]
    Останній стовпець: [ 9.9 -0.7  4.8  5.1]
Потрібно задавати два значення для отримання конкретного елемента:
    Перший елемент: 3.4 або 3.4
    Останній елемент: 5.1 або 5.1 або 5.1


>>>>> Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементів які належать діагоналі. 

3.4
-7.8
4.8


IndexError: index 3 is out of bounds for axis 0 with size 3

In [26]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(f"""Масив:
{S}
Виміри: {S.shape}
Беремо декілька елементів: {S[2:5]}
Всі елементи до заданого: {S[:4]}
Всі елементи від заданого до кінця: {S[6:]}
Всі елементи: {S[:]}
""")
homework("Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву.")
print(S[-4:])

Масив:
[0 1 2 3 4 5 6 7 8 9]
Виміри: (10,)
Беремо декілька елементів: [2 3 4]
Всі елементи до заданого: [0 1 2 3]
Всі елементи від заданого до кінця: [6 7 8 9]
Всі елементи: [0 1 2 3 4 5 6 7 8 9]


>>>>> Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву. 

[6 7 8 9]


In [ ]:
A = np.array([
    [11, 12, 13, 14, 15],
    [21, 22, 23, 24, 25],
    [31, 32, 33, 34, 35],
    [41, 42, 43, 44, 45],
    [51, 52, 53, 54, 55]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо декілька рядків:
{A[0:2]}
Два перші стовпці:
{A[:, 0:2]}
Два останні рядки:
{A[3:, :]}
Беремо підматрицю (нижні елементи):
{A[-3:, -3:]}
""")
homework("Попрактикуйтесь у витягуванні елементів, візьміть матрицю 2х2 з нижнього та верхнього кутка матриці А.")upper_corner = A[0:2, 0:2]
lower_corner = A[-2:,-2:]

print("Upper Corner:")
print(upper_corner)
print("Lower Corner:")
print(lower_corner)

In [ ]:
A = np.arange(28).reshape(4, 7)

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо кожен дугий елемент першого рядка:
{A[0, ::2]}
Беремо кожен третій елемент першого рядка:
{A[0, ::3]}
Кожен другий елемент в кожномуу другому рядку:
{A[::2, ::2]}
Останні три елементи в кожному другому рядку:
{A[::2, 4:]}
Можна повнісню змінити порядок елементів (дзерально обернемо):
{A[::-1, ::-1]}
""")

homework("Попрактикуйтесь у витягуванні елементів, будь-яка робоча комбінація.")
print(A[2,:])
print(A[1, 2])
print(A[1:3, 1:5])


In [28]:
A = np.arange(50)
all_even = (A%2==0) # парні
complex = (A<30) & (A/5<2)

print(f"""Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або {all_even[0]} для {A[0]} або {all_even[1]} для {A[1]}.
Після підставляння умови пошуку парних чисел в масив отримаємо:
{A[all_even]}
Або застосувавти більш комплексну умову з двох порінянь:
{A[complex]}""")

homework("Виведіть всі непарні числа з даного масиву.")
odd_numbers = A[A % 2 != 0]
print(odd_numbers)


Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або True для 0 або False для 1.
Після підставляння умови пошуку парних чисел в масив отримаємо:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
Або застосувавти більш комплексну умову з двох порінянь:
[0 1 2 3 4 5 6 7 8 9]

>>>>> Виведіть всі непарні числа з даного масиву. 



TypeError: unhashable type: 'numpy.ndarray'

In [ ]:
o = np.ones(5)
z = np.zeros(5)
i = np.identity(5)
e = np.eye(5)
t = np.empty(5)

print(f"""
Всі елементи 1:
{o}
Всі елементи 0:
{z}
Матриця в якої діагональ всі 1:
{i}
Також, діагональ всі 1 (зменшимо вивід):
{e[:2, :2]}
Пуста матриця буде містити набір випадкових чисел які записані у память де був ініціалізований масив:
{t}
""")