In [17]:
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np

In [18]:
l = (3, 3)

O = np.ones(l)
R = np.random.random(l)
Z = np.zeros(l)
C = np.arange(l[0])

print(f"""
Віднімання:\n {C - (O + 10)}
Множення:\n {O * R}
Ділення:\n {R / C}
Степінь:\n {C ** Z}
Поріняння:\n {R > 0.5}
Ділення на 0:\n {O / Z}
""")
homework("""
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
""")

matrix = np.eye(3)
print("Створена матриця:\n", matrix)

result = np.where(matrix == 1)
print("Індекси елементів рівних 1:\n", result)
eye_matrix = np.eye(5)
ones_matrix = np.ones((5,5))
result = ones_matrix - eye_matrix
print(result)


Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.75541403 0.19034449 0.35498883]
 [0.0340657  0.68855839 0.36583843]
 [0.21114658 0.78503473 0.42378713]]
Ділення:
 [[       inf 0.19034449 0.17749442]
 [       inf 0.68855839 0.18291922]
 [       inf 0.78503473 0.21189357]]
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Поріняння:
 [[ True False False]
 [False  True False]
 [False  True False]]
Ділення на 0:
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


>>>>> 
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
 

Створена матриця:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Індекси елементів рівних 1:
 (array([0, 1, 2], dtype=int64), array([0, 1, 2], dtype=int64))
[[0. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0.]]


C:\Users\yurar\AppData\Local\Temp\ipykernel_6664\1273225765.py:11: RuntimeWarning: divide by zero encountered in divide
  Ділення:\n {R / C}
C:\Users\yurar\AppData\Local\Temp\ipykernel_6664\1273225765.py:14: RuntimeWarning: divide by zero encountered in divide
  Ділення на 0:\n {O / Z}


In [19]:
A = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B = np.array([ [3, 2, 1], [1, 2, 3], [-1, -2, -3] ])
print(f"Маємо два масиви:\n {A} \n {B}")

R = A * B
print(f"Тут виконується поелементне множення:\n {R}")

R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n {R}")

MA = np.mat(A)
MB = np.mat(B)

R = MA * MB
print(f"Тут масиви перетворені на матриці і далі перемножуються:\n {R}")

Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 
 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


In [20]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]

print(f"Вектор В є рядком {B.shape}: {B} тому додавання буде по рядках:\n {A + B}")

print(f"""Вектор C є стовпцем {C.shape}:
{C}
тому додавання буде по стовпцям:
{A + C}""")

print(f"У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:\n {B + C}")

Вектор В є рядком (3,): [1 2 3] тому додавання буде по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]
Вектор C є стовпцем (3, 1):
[[1]
 [2]
 [3]]
тому додавання буде по стовпцям:
[[12 13 14]
 [23 24 25]
 [34 35 36]]
У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [23]:
# D = np.ones(3)
# Z = np.zeros((3,1))
# print(f"""
# При конкатенації рядків маємо: {np.concatenate((D, D))}")
# При конкатенації стовпців маємо:\n{np.concatenate((Z, Z))}
# Масив D {D} має розмірність {D.shape} тому може виконати операцію конкатенації з В {B} розмірністю {B.shape}:
# {np.concatenate((B, D))}
# Для конкатенації з С
# {C}
# де С має розмірність = {C.shape} потрібно змінити розмірність D = {D.shape}
# Це можна ось так:
# {D[:, np.newaxis].shape}
# або
# {D.reshape((3,1)).shape}
# в результаті ми можем виконати конкатенацію:
# {np.concatenate((C, D.reshape((3,1))))}
# При повторенні D {D} 2 рази для рядкі та 3 для стовпців будем мати:
# {np.tile(D, (2, 3))}
# Як бачимо конкатенація та повторення є дещо схожими у деяких випадках:
# - конкатенація: {np.concatenate((D, D))}
# - повторення: {np.tile(D, 2)}
# Також можна перетворити двовимірний масив A розмірністю {A.shape} на рядок: {A.flatten()} з розмірністю {A.flatten().shape}
# """)
#
#
#
# homework(f"""Створіть двохвимірний масив за допомогою arange та виконайте конкатенацію та повторення.
# Створіть масив в якому кількість рядкі та стовпців різна. Спробуйте виконати конкатенацію такого масиву з попереднім. Якщо розмірність масивів не спаівпадє використайте reshape.
# Створіть декіль двовимірних масивів з сумарною розмірністю 12 та знайдіть всі можливі комбінції reshape. Наприклад, перша комбінація це рядок - {np.ones((1,12))}
# """)
#
# import numpy as np

# Create a 2-dimensional array with arange
a = np.arange(9).reshape(3,3)

# Concatenate two 2-dimensional arrays horizontally
b = np.concatenate((a, a), axis=1)

# Repeat the 2-dimensional array
c = np.repeat(A, 2, axis=0)
import numpy as np

# Create two arrays with different shapes
a = np.arange(9).reshape(3,3)
b = np.arange(4).reshape(2,2)

# Reshape the second array to match the shape of the first array
b = b.reshape(3,2)


c = np.concatenate((a, b), axis=1)
import numpy as np


arrays = [np.ones((2,6)), np.ones((3,4)), np.ones((4,3)), np.ones((6,2))]


for arr in arrays:
    for i in range(1,13):
        try:
            reshaped = arr.reshape(i,12//i)
            print(f"Array of shape {arr.shape} reshaped to {reshaped.shape}")
        except:
            pass



ValueError: cannot reshape array of size 4 into shape (3,2)

In [25]:
O = np.arange(6).reshape(3,2)
O_r = O.reshape((2,3))
O_f = O.flatten()
O_t = O.transpose()
O_fl = np.flip(O)
O_fa = np.flip(O, axis=1)

print(f"""{O}
Змінити розмірність shape {O.shape} на {O_r.shape} при цьому розмір size {O.size} = {O_r.size} та ndim {np.ndim(O)} = {np.ndim(O_r)}:
{O_r}
Також можна перетворити {np.ndim(O)}-х вимірний масив розмірністю {O.shape} на рядок:
{O_f}
з розмірністю {O_f.shape} при цьому size = {O_f.size} та ndim стане {np.ndim(O_f)}-х вимірним
Або транспонувати масив щоб він став {O_t.shape} але зверніть увагу на елементи:
{O_t}
Можна обернути масив (обертаємо по стовпцях і рядках одночасно):
{O_fl}
Або обернути лише елементи в кожному рядку (або стовпці):
{O_fa}
""")

homework("""
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірніть перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
""")
# Create a 12-element vector
vector = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

vector_shape = vector.shape
vector_size = vector.size
vector_ndim = vector.ndim
vector = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
matrix = vector.reshape(3, 4)
print(matrix)
vector = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
matrix = vector.reshape(3, 4)
matrix_transposed = matrix.T
matrix_reversed = matrix_transposed[::-1]
# Create a 12-element vector
vector = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

matrix = vector.reshape(3, 4)
matrix_transposed = matrix.T
matrix_reversed = matrix_transposed[::-1]

vector_back = matrix_reversed.reshape(-1)
print(vector_back)

[[0 1]
 [2 3]
 [4 5]]
Змінити розмірність shape (3, 2) на (2, 3) при цьому розмір size 6 = 6 та ndim 2 = 2:
[[0 1 2]
 [3 4 5]]
Також можна перетворити 2-х вимірний масив розмірністю (3, 2) на рядок:
[0 1 2 3 4 5]
з розмірністю (6,) при цьому size = 6 та ndim стане 1-х вимірним
Або транспонувати масив щоб він став (2, 3) але зверніть увагу на елементи:
[[0 2 4]
 [1 3 5]]
Можна обернути масив (обертаємо по стовпцях і рядках одночасно):
[[5 4]
 [3 2]
 [1 0]]
Або обернути лише елементи в кожному рядку (або стовпці):
[[1 0]
 [3 2]
 [5 4]]


>>>>> 
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірніть перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 3  7 11  2  6 10  1  5  9  0  4  8]
